# Generated by Django 5.0.6 on 2024-06-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='map',
            name='id',
        ),
        migrations.AlterField(
            model_name='agent',
            name='name_en',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='map',
            name='name_en',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
